#name: Continuous Deployment
#
#on:
#  push:
#    branches:
#      - main  # 根据实际情况调整分支名称
#  pull_request:
#    branches:
#      - main
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Check out code
#        uses: actions/checkout@v3
#
#      - name: Set up JDK 22
#        uses: actions/setup-java@v2
#        with:
#          java-version: '22'  # 根据你的项目实际使用的JDK版本调整
#          distribution: 'temurin'
#
#      - name: Build with Maven
#        run: mvn clean install -DskipTests  # 根据需要调整Maven命令
#
#      - name: Copy files to the server
#        uses: appleboy/scp-action@master
#        with:
#          host: ${{ secrets.REMOTE_HOST }}
#          username: ${{ secrets.REMOTE_USER }}
#          password: ${{ secrets.REMOTE_PASSWORD }}
#          port: ${{ secrets.REMOTE_PORT }}
#          source: "target/*.jar"
#          target: "/path/to/your/server/directory"
#
#      - name: Restart server
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.REMOTE_HOST }}
#          username: ${{ secrets.REMOTE_USER }}
#          password: ${{ secrets.REMOTE_PASSWORD }}
#          port: ${{ secrets.REMOTE_PORT }}
#          script: |
#            cd /path/to/your/server/directory
#            ./restart-server.sh  # 你的重启脚本
