name: CI/CD Pipeline
#1
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'       # 忽略所有 Markdown 文件
      - '**/*.txt'      # 忽略所有文本文件
      - '**/*.sh'       # 忽略所有 shell 脚本
#      - '**/*.yml'      # 忽略所有 YAML 文件
      - '**/docs/**'    # 忽略 docs 目录中的所有文件
      - 'databaseSQL/**'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server:
          - { name: "Server 1", ip: "121.36.220.232" }
          - { name: "Server 2", ip: "121.37.187.80" }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test with Maven
        run: mvn -B package --file jiaoji_backend/jiaoji/pom.xml || { echo 'Build failed'; exit 1; }

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Stop Application on ${{ matrix.server.name }}
        run: |
          ssh -o StrictHostKeyChecking=accept-new root@${{ matrix.server.ip }} 'bash -s' < ./scripts/stop-app.sh || { echo 'Stop failed'; exit 1; }

      - name: Copy files to ${{ matrix.server.name }}
        run: |
          scp -o StrictHostKeyChecking=accept-new jiaoji_backend/jiaoji/target/jiaoji-0.0.1-SNAPSHOT.jar root@${{ matrix.server.ip }}:/www/wwwroot/jiaoji || { echo 'Copy failed'; exit 1; }

      - name: Restart Application on ${{ matrix.server.name }}
        run: |
          ssh -o StrictHostKeyChecking=accept-new root@${{ matrix.server.ip }} 'bash -s' < ./scripts/restart-app.sh || { echo 'Restart failed'; exit 1; }

