name: CI/CD Pipeline
# 5
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven
      - name: Build and Test with Maven
        run: mvn -B package --file jiaoji_backend/jiaoji/pom.xml # Updated path to the pom.xml
      - name: List target directory
        run: ls -la jiaoji_backend/jiaoji/target # Update to the correct path
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: jiaoji-jar
          path: jiaoji_backend/jiaoji/target/jiaoji-0.0.1-SNAPSHOT.jar # Update to the correct path

  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: jiaoji-jar
          path: target
      - name: List target directory
        run: ls -la target
      - name: Copy files via SSH
        run: scp -o StrictHostKeyChecking=no target/jiaoji-0.0.1-SNAPSHOT.jar root@124.70.209.108:/www/wwwroot/jiaoji
      - name: Restart Application
        run: ssh root@124.70.209.108 'bash -s' < ./scripts/restart-app.sh
