name: CI/CD Pipeline
# 19
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'       # 忽略所有 Markdown 文件
      - '**/*.txt'      # 忽略所有文本文件
      - '**/docs/**'    # 忽略 docs 目录中的所有文件
#      - '.github/**'
      - 'databaseSQL/**'
      - 'scripts/**'
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test with Maven
        run: mvn -B package --file jiaoji_backend/jiaoji/pom.xml # Updated path to the pom.xml

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: jiaoji-jar
          path: jiaoji_backend/jiaoji/target/jiaoji-0.0.1-SNAPSHOT.jar # Update to the correct path

  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
     - uses: actions/checkout@v4  # Ensure all files, including scripts, are available

     - name: Install SSH key
       uses: webfactory/ssh-agent@v0.5.3
       with:
         ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

     - name: Download artifact
       uses: actions/download-artifact@v3
       with:
         name: jiaoji-jar
         path: target

     - name: Stop Application
       run: ssh -o StrictHostKeyChecking=no root@121.36.220.232 'bash -s' < ./scripts/stop-app.sh
      #  run: ssh -o StrictHostKeyChecking=no root@121.36.220.232 'bash scripts/stop-app.sh'

    #  - name: Copy files via SSH
    #    run: scp -o StrictHostKeyChecking=no target/jiaoji-0.0.1-SNAPSHOT.jar root@121.36.220.232:/www/wwwroot/jiaoji

     - name: Restart Application
       run: ssh -o StrictHostKeyChecking=no root@121.36.220.232 'bash -s' < ./scripts/restart-app.sh
      #  run: ssh -o StrictHostKeyChecking=no root@121.36.220.232 'bash scripts/restart-app.sh'
